### ISSUE TITLE
Recommended way to pass in a standard

### ISSUE THREAD

**Issue by mjoyce91** [pa11y/ci#25]
What's the recommended way to pass in a standard to `pa11y-ci`? For example, with regular pa11y, I can run `pa11y --standard 'WCAG2AA' 'someurl.com'`. Can I do something similar with pa11y-ci? Maybe in the `.pa11y-ci` config file? Seems like it's defaulting to 508.

**Comment by rowanmanning** [comment]
That's odd, it should default to `WCAG2AA`. But yes the `.pa11y-ci` config file is the best place to put it. Something like this:

```json
{
    "defaults": {
        "standard": "WCAG2AAA"
    },
    "urls": [
        "https://example.com/"
    ]
}
```
